[theme]
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#111827"

[server]
maxUploadSize = 25
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false 